// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEbRFta5aqvy-78ubYgqqZIycsd6C37x0',
    appId: '1:288663738760:android:08d0af41ee6e2b4b8ec23d',
    messagingSenderId: '288663738760',
    projectId: 'fasilitas-umum-ac9ea',
    storageBucket: 'fasilitas-umum-ac9ea.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcs7QhbiPhFjM86Oqe2Y4R3j7mZJvwyic',
    appId: '1:288663738760:web:45c77f3e996dbd7b8ec23d',
    messagingSenderId: '288663738760',
    projectId: 'fasilitas-umum-ac9ea',
    authDomain: 'fasilitas-umum-ac9ea.firebaseapp.com',
    storageBucket: 'fasilitas-umum-ac9ea.firebasestorage.app',
    measurementId: 'G-VDXXEMT2Q3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrUfb-_kafrcPRRQJ4V_xNWXEWlDGMtdM',
    appId: '1:288663738760:ios:66c9764863534c128ec23d',
    messagingSenderId: '288663738760',
    projectId: 'fasilitas-umum-ac9ea',
    storageBucket: 'fasilitas-umum-ac9ea.firebasestorage.app',
    iosBundleId: 'com.example.fasilitasUmum',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrUfb-_kafrcPRRQJ4V_xNWXEWlDGMtdM',
    appId: '1:288663738760:ios:66c9764863534c128ec23d',
    messagingSenderId: '288663738760',
    projectId: 'fasilitas-umum-ac9ea',
    storageBucket: 'fasilitas-umum-ac9ea.firebasestorage.app',
    iosBundleId: 'com.example.fasilitasUmum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcs7QhbiPhFjM86Oqe2Y4R3j7mZJvwyic',
    appId: '1:288663738760:web:8f9a290f9e686b8a8ec23d',
    messagingSenderId: '288663738760',
    projectId: 'fasilitas-umum-ac9ea',
    authDomain: 'fasilitas-umum-ac9ea.firebaseapp.com',
    storageBucket: 'fasilitas-umum-ac9ea.firebasestorage.app',
    measurementId: 'G-DRRDQR5X1J',
  );

}